baseURL = "https://ichris.info"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "Chris's web"
theme = "beautifulhugo"
enableEmoji = true
# enableGitInfo = true
hasCJKLanguage = true
paginate = 10
paginatePath = "page"
googleAnalytics = "UA-137163651-1"
# uglyURLs = true

pygmentsOptions = "linenos=table"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[Params]
	useHLJS = false
	since = 2011
	subtitle = "简洁 优雅 高效"
	logo = "/img/avatar.jpg"
	favicon = "/img/favicon.ico"
	dateFormat = "2006-01-02"

[Author]
	name = "Chris"
	github = "ichrislu"
	email = "chrislu.name@gmail.com"

[blackfriday]
	hrefTargetBlank = true

[[menu.main]]
	name = "HOME"
	url = ""
	weight = 1

[[menu.main]]
	name = "Categories"
	url = "categories"
	weight = 2

[[menu.main]]
	name = "Tags"
	url = "tags"
	weight = 3

[[menu.main]]
	name = "About"
	url = "about"
	weight = 4

[permalinks]
	"/" = "/:year/:title/"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]

[outputs]
	home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
	baseName = "algolia"
	isPlainText = true
	mediaType = "application/json"
	notAlternative = true
