baseURL = "https://ichris.info/"
languageCode = "zh-CN"
defaultContentLanguage = "zh-CN"
title = "Chris's web"
theme = "beautifulhugo"
enableEmoji = true
# enableGitInfo = true
hasCJKLanguage = true

# 代码语法高亮
pygmentsOptions = "linenos=table"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[params]
	useHLJS = false
	since = 2011
	subtitle = "简洁 优雅 高效"
	logo = "/img/avatar.jpg"
	favicon = "/img/favicon.ico"
	dateFormat = "2006-01-02"

[params.author]
	name = "Chris"
	github = "ichrislu"
	email = "chrislu.name@gmail.com"

[pagination]
	pagerSize = 10
	path = 'page'

[[menu.main]]
	name = "HOME"
	url = ""
	weight = 1

[[menu.main]]
	name = "Categories"
	url = "categories"
	weight = 2

[[menu.main]]
	name = "Tags"
	url = "tags"
	weight = 3

[[menu.main]]
	name = "About"
	url = "about"
	weight = 4

[permalinks]
	"/" = "/:year/:title/"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]

[outputs]
	home = ["Algolia"]

[outputFormats.Algolia]
	baseName = "algolia"
	isPlainText = true
	mediaType = "application/json"
	notAlternative = true
