baseURL = "https://ichris.info/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "Chris's web"
theme = "beautifulhugo"
enableEmoji = true
# enableGitInfo = true
hasCJKLanguage = true
enableRobotsTXT = true

# 代码语法高亮
pygmentsOptions = "linenos=table"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[params]
	useHLJS = false
	since = 2011
	subtitle = "简洁 优雅 高效"
	logo = "/img/avatar.jpg"
	favicon = "/img/favicon.ico"
	dateFormat = "2006-01-02"
  [params.author]
    email = 'chrislu.name@gmail.com'
    phone = '+1 202-555-1212'
    name = "Chris"
    github = "ichrislu"

# [params.author]
#	name = "Chris"
#	github = "ichrislu"
#	email = "chrislu.name@gmail.com"

[pagination]
	pagerSize = 10
	path = 'page'

[menus]
	[[menus.main]]
		name = "HOME"
		pageRef = "/"
		weight = 1

	[[menus.main]]
		name = "Categories"
		pageRef = "/categories"
		weight = 2

	[[menus.main]]
		name = "Tags"
		pageRef = "/tags"
		weight = 3

	[[menus.main]]
		name = "About"
		pageRef = "/about"
		weight = 4

[permalinks]
	"/" = "/:year/:title/"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]

[outputs]
	home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
	baseName = "algolia"
	isPlainText = true
	mediaType = "application/json"
	notAlternative = true
